import {
  Banknote,
  Book,
  Bus,
  Car,
  CreditCard,
  Dog,
  Dumbbell,
  Ellipsis,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Leaf,
  type LucideIcon,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Plane,
  Plus,
  Receipt,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Tag,
  Ticket,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
} from "lucide-react";

/** Curated icon set offered in the category picker. */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  tag: Tag,
  wallet: Wallet,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  "trending-up": TrendingUp,
  landmark: Landmark,
  home: Home,
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  book: Book,
  laptop: Laptop,
  wifi: Wifi,
  repeat: Repeat,
  "party-popper": PartyPopper,
  gamepad: Gamepad2,
  ticket: Ticket,
  gift: Gift,
  "paw-print": PawPrint,
  dog: Dog,
  leaf: Leaf,
  wrench: Wrench,
  receipt: Receipt,
  sparkles: Sparkles,
  plus: Plus,
  ellipsis: Ellipsis,
};

export const ICON_NAMES = Object.keys(ICON_REGISTRY);

export function getCategoryIcon(name: string | null | undefined): LucideIcon {
  return (name && ICON_REGISTRY[name]) || Tag;
}
